//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaIntelitech.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturas
    {
        public int IdDetalleFactura { get; set; }
        public Nullable<int> IdProducto_FK { get; set; }
        public Nullable<int> IdFactura_FK { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
